apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cortex-operator
  template:
    metadata:
      labels:
        name: cortex-operator
    spec:
      serviceAccountName: cortex-operator
      containers:
        - name: cortex-operator
          # Replace this with the built image name
          image: vineeth97/cortex-operator:v0.0.1
          command:
          - cortex-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cortex-operator"
